### ISSUE TITLE
Add Code Block Styling + Mermaid + Mathjax Support

### ISSUE THREAD

**Issue by bliutech** [pbrucla/pbrucla.github.io#10]
- [x] add code block styling support http://jwarby.github.io/jekyll-pygments-themes/languages/java.html
- [ ] add mermaid support https://mermaid-js.github.io/mermaid/#/
- [x] add mathjax support https://docs.mathjax.org/en/latest/input/tex/html.html

**Comment by bliutech** [comment]
Started looking into this instead for Code Blocks. https://highlightjs.org/ This is what HackMD uses and it seems more robust.

**Comment by Arc-blroth** [comment]
The other day I discovered https://katex.org/, Khan Academy's LaTeX library, which claims to be faster than MathJax - perhaps we should try using that instead of MathJax?

**Comment by bliutech** [comment]
@Arc-blroth quick clarification. I believe KaTeX is actually a different syntax from LaTeX. For these reasons, I think I want to stick to MathJax. LaTeX is a bit more appealing and well known. KaTeX would require people to learn a new syntax which I don't think is appealing. More details here. https://tex.stackexchange.com/questions/648196/whats-the-difference-between-different-latex-versions-like-livetex-katex-macte

**Comment by bliutech** [comment]
Mermaid graphs are not going to be used frequently so will mark this issue as complete for now. Will reopen if we see the need for Mermaid.
